import { UserRole, type IApplication } from "@/types";

export const applications: IApplication[] = [
  {
    id: 1,
    fullName: "Gagik Asatryan",
    email: "gag.asatryan@gmail.com",
    role: UserRole.LECTURER,
    age: 32,
  },
  {
    id: 2,
    fullName: "Anush Gevorgyan",
    email: "anush.gevorgyan@gmail.com",
    role: UserRole.LECTURER,
    age: 16,
  },
  {
    id: 3,
    fullName: "Armen Hakobyan",
    email: "armen.hakobyan@gmail.com",
    role: UserRole.STUDENT,
    age: 21,
  },
  {
    id: 4,
    fullName: "Siranush Avetisyan",
    email: "siranush.avetisyan@gmail.com",
    role: UserRole.STUDENT,
    age: 19,
  },
  {
    id: 5,
    fullName: "Levon Petrosyan",
    email: "levon.petrosyan@gmail.com",
    role: UserRole.LECTURER,
    age: 45,
  },
  {
    id: 6,
    fullName: "Mariam Sargsyan",
    email: "mariam.sargsyan@gmail.com",
    role: UserRole.STUDENT,
    age: 22,
  },
  {
    id: 7,
    fullName: "Hayk Harutyunyan",
    email: "hayk.harutyunyan@gmail.com",
    role: UserRole.LECTURER,
    age: 38,
  },
  {
    id: 8,
    fullName: "Narine Khachatryan",
    email: "narine.khachatryan@gmail.com",
    role: UserRole.STUDENT,
    age: 20,
  },
  {
    id: 9,
    fullName: "Tigran Vardanyan",
    email: "tigran.vardanyan@gmail.com",
    role: UserRole.STUDENT,
    age: 23,
  },
  {
    id: 10,
    fullName: "Ani Davtyan",
    email: "ani.davtyan@gmail.com",
    role: UserRole.LECTURER,
    age: 35,
  },
  {
    id: 11,
    fullName: "Gor Stepanyan",
    email: "gor.stepanyan@gmail.com",
    role: UserRole.STUDENT,
    age: 24,
  },
  {
    id: 12,
    fullName: "Lilit Grigoryan",
    email: "lilit.grigoryan@gmail.com",
    role: UserRole.STUDENT,
    age: 18,
  },
];
