export const courses = [
  {
    id: 1,
    title: "Programming",
    start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
    end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 120),
    topics: [
      {
        id: 1,
        title: "C Programming Language",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15),
        specialist: {
          id: 23,
          fullName: "Andranik Avagyan",
          phoneNumber: "+37477073464",
          email: "andranik.avagyan@example.com",
          gender: "արական",
          age: 28,
          picture:
            "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992",
        },
      },
      {
        id: 2,
        title: "Algorithms",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 16),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
      },
      {
        id: 3,
        title: "Database Internals",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 31),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
      },
      {
        id: 4,
        title: "C# .NET",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 46),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 70),
      },
    ],
    lecturers: [
      {
        id: 1,
        fullName: "Mariam Petrosyan",
        expertise: "Software Engineering",
        age: 34,
        gender: "իգական",
        email: "mariam.petrosyan@example.com",
        phoneNumber: "+37477551234",
        picture: "https://randomuser.me/api/portraits/women/60.jpg",
      },
      {
        id: 2,
        fullName: "Armen Hakobyan",
        expertise: "Computer Science",
        age: 41,
        gender: "արական",
        email: "armen.hakobyan@example.com",
        phoneNumber: "+37477662345",
        picture: "https://randomuser.me/api/portraits/men/52.jpg",
      },
    ],
    students: [
      {
        id: 101,
        fullName: "Narek Sargsyan",
        age: 21,
        gender: "արական",
        email: "narek.sargsyan@example.com",
        phoneNumber: "+37477111222",
      },
      {
        id: 102,
        fullName: "Lilit Grigoryan",
        age: 22,
        gender: "իգական",
        email: "lilit.grigoryan@example.com",
        phoneNumber: "+37477333444",
      },
      {
        id: 103,
        fullName: "Hayk Harutyunyan",
        age: 23,
        gender: "արական",
        email: "hayk.harutyunyan@example.com",
        phoneNumber: "+37477555666",
      },
    ],
  },
  {
    id: 2,
    title: "Frontend Development",
    start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
    end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90),
    topics: [
      {
        id: 1,
        title: "HTML & CSS Fundamentals",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15),
        specialist: {
          id: 25,
          fullName: "Siranush Avetisyan",
          phoneNumber: "+37477456321",
          email: "siranush.avetisyan@example.com",
          gender: "իգական",
          age: 27,
          picture: "https://randomuser.me/api/portraits/women/68.jpg",
        },
      },
      {
        id: 2,
        title: "JavaScript Essentials",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 16),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35),
      },
      {
        id: 3,
        title: "React.js Framework",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 36),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 55),
      },
      {
        id: 4,
        title: "TypeScript & State Management",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 56),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 75),
      },
    ],
    lecturers: [
      {
        id: 3,
        fullName: "Avo Boyakhchyan",
        expertise: "React / TypeScript / Tailwind CSS",
        age: 26,
        gender: "արական",
        email: "avo.boyakhchyan@example.com",
        phoneNumber: "+37477001234",
        picture: "https://randomuser.me/api/portraits/men/36.jpg",
      },
    ],
    students: [
      {
        id: 104,
        fullName: "Anna Hakobyan",
        age: 20,
        gender: "իգական",
        email: "anna.hakobyan@example.com",
        phoneNumber: "+37477099888",
      },
      {
        id: 105,
        fullName: "Karen Stepanyan",
        age: 21,
        gender: "արական",
        email: "karen.stepanyan@example.com",
        phoneNumber: "+37477222777",
      },
      {
        id: 106,
        fullName: "Sona Martirosyan",
        age: 22,
        gender: "իգական",
        email: "sona.martirosyan@example.com",
        phoneNumber: "+37477333999",
      },
      {
        id: 107,
        fullName: "Gor Petrosyan",
        age: 23,
        gender: "արական",
        email: "gor.petrosyan@example.com",
        phoneNumber: "+37477444888",
      },
    ],
  },
  {
    id: 3,
    title: "Backend Development",
    start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10),
    end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 130),
    topics: [
      {
        id: 1,
        title: "Node.js Fundamentals",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25),
        specialist: {
          id: 30,
          fullName: "David Ghazaryan",
          phoneNumber: "+37477984211",
          email: "david.ghazaryan@example.com",
          gender: "արական",
          age: 33,
          picture: "https://randomuser.me/api/portraits/men/55.jpg",
        },
      },
      {
        id: 2,
        title: "Databases & ORMs",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 26),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45),
      },
      {
        id: 3,
        title: "RESTful APIs with Express",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 46),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 65),
      },
      {
        id: 4,
        title: "Docker & Deployment",
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 66),
        end_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 85),
      },
    ],
    lecturers: [
      {
        id: 4,
        fullName: "Ani Davtyan",
        expertise: "Node.js / SQL / Docker",
        age: 32,
        gender: "իգական",
        email: "ani.davtyan@example.com",
        phoneNumber: "+37477551212",
        picture: "https://randomuser.me/api/portraits/women/48.jpg",
      },
    ],
    students: [
      {
        id: 108,
        fullName: "Artur Vardanyan",
        age: 25,
        gender: "արական",
        email: "artur.vardanyan@example.com",
        phoneNumber: "+37477991111",
      },
      {
        id: 109,
        fullName: "Mariam Sargsyan",
        age: 24,
        gender: "իգական",
        email: "mariam.sargsyan@example.com",
        phoneNumber: "+37477101010",
      },
      {
        id: 110,
        fullName: "Levon Manukyan",
        age: 26,
        gender: "արական",
        email: "levon.manukyan@example.com",
        phoneNumber: "+37477202020",
      },
    ],
  },
];
