import type { IDocument } from "@/types";

export const CV_TEMPLATES: IDocument[] = [
  {
    id: 1001,
    title: "Կլասիկ պարզություն",
    backgroundColor: "#FFFFFF",
    isEditMode: false,
    dimension: {
      format: "a4",
      title: "A4",
      width: 794,
      height: 1123,
      preview: { width: 248, height: 350 },
    },
    contentBlocks: [
      {
        id: 1101,
        top: 80,
        left: 90,
        width: 420,
        height: 110,
        rotation: 0,
        zIndex: 1,
        contentType: "title",
        defaultContent: "Լրացրե՛ք անունը",
        content: "Արմեն Խաչատրյան",
        fontSize: 46,
        fontWeight: "700",
        color: "#0F172A",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 1102,
        top: 210,
        left: 90,
        width: 460,
        height: 160,
        rotation: 0,
        zIndex: 1,
        contentType: "description",
        defaultContent: "Կարճ նկարագրություն",
        content:
          "Տվյալագիտության մասնագետ՝ 6 տարվա փորձով։ Սիրում եմ բարդ խնդիրները բաժանել պարզ քայլերի և կառուցել տվյալահենք լուծումներ, որոնք օգնում են բիզնեսին աճել։",
        fontSize: 18,
        fontWeight: "400",
        color: "#1E293B",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 1103,
        top: 400,
        left: 90,
        width: 560,
        height: 260,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "Աշխատանքային փորձ",
        content: `<strong>Տվյալագիտության թիմի ղեկավար · DataForge</strong><br/>
2021 — ներկայում<br/>
- Ղեկավարել եմ 8 մասնագետից բաղկացած թիմը՝ բանկային ոլորտի նախագծերում։<br/>
- Տեղականացրել եմ ML մոդելներ, որոնք ավելացրել են եկամուտը 17%-ով։<br/><br/>
<strong>Տվյալագիտության վերլուծաբան · ArmAnalytics</strong><br/>
2018 — 2021<br/>
- Ստեղծել եմ ավտոմատացված հաշվետվություններ Power BI-ով։<br/>
- Իրականացրել եմ օգտագործող-կլասթերացում՝ CRM արշավների օպտիմալացման համար։`,
        fontSize: 16,
        fontWeight: "400",
        color: "#1F2937",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 1104,
        top: 700,
        left: 90,
        width: 560,
        height: 190,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "Կրթություն և հմտություններ",
        content: `<strong>Կրթություն</strong><br/>
ԵՊՀ · Կիրառական մաթեմատիկա և ինֆորմատիկա<br/>
2013 — 2017<br/><br/>
<strong>Հմտություններ</strong><br/>
Python · SQL · TensorFlow · Docker · Agile · Armenian/English/Russian`,
        fontSize: 16,
        fontWeight: "400",
        color: "#1F2937",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
    ],
    imageBlocks: [
      {
        id: 1201,
        top: 80,
        left: 560,
        width: 150,
        height: 150,
        rotation: 0,
        zIndex: 2,
        path: "https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        isEditMode: false,
      },
    ],
    shapeBlocks: [
      {
        id: 1301,
        top: 360,
        left: 90,
        width: 560,
        height: 3,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#E2E8F0",
        borderColor: "#E2E8F0",
        isEditMode: false,
      },
      {
        id: 1302,
        top: 660,
        left: 90,
        width: 560,
        height: 3,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#E2E8F0",
        borderColor: "#E2E8F0",
        isEditMode: false,
      },
    ],
  },
  {
    id: 2001,
    title: "Ժամանակակից գունային",
    backgroundColor: "#0F172A",
    isEditMode: false,
    dimension: {
      format: "a4",
      title: "A4",
      width: 794,
      height: 1023,
      preview: { width: 248, height: 350 },
    },
    contentBlocks: [
      {
        id: 2101,
        top: 120,
        left: 80,
        width: 400,
        height: 120,
        rotation: 0,
        zIndex: 1,
        contentType: "title",
        defaultContent: "Անունը",
        content: "Մարիա Ավագյան",
        fontSize: 44,
        fontWeight: "700",
        color: "#FFFFFF",
        backgroundColor: "transparent",
        fontFamily: "Manrope",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 2102,
        top: 250,
        left: 80,
        width: 420,
        height: 140,
        rotation: 0,
        zIndex: 1,
        contentType: "description",
        defaultContent: "",
        content:
          "UI/UX դիզայներ՝ կենտրոնացած բրենդավորված թվային փորձառությունների վրա։ Հավատում եմ, որ լավ դիզայնը պետք է լինի ինչպես էսթետիկ, այնպես էլ խիստ օգտակար։",
        fontSize: 18,
        fontWeight: "400",
        color: "#CBD5F5",
        backgroundColor: "transparent",
        fontFamily: "Manrope",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 2103,
        top: 420,
        left: 80,
        width: 620,
        height: 280,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Կարևոր նախագծեր</strong><br/>
• <em>Armenia Travel</em> — Վերակառուցված UI, որը բարձրացրել է կանխավճարները 30%-ով։<br/>
• <em>MedLink</em> — Դիզայն-սիստեմ՝ հիվանդանոցային SaaS-ի համար։<br/><br/>
<strong>Թիմային գործիքներ</strong><br/>
Figma · FigJam · Notion · Zeplin · Jira`,
        fontSize: 17,
        fontWeight: "400",
        color: "#E0E7FF",
        backgroundColor: "transparent",
        fontFamily: "Manrope",
        textAlign: "left",
        isEditMode: false,
      },
    ],
    imageBlocks: [
      {
        id: 2201,
        top: 110,
        left: 540,
        width: 170,
        height: 170,
        rotation: 0,
        zIndex: 2,
        path: "https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        isEditMode: false,
      },
    ],
    shapeBlocks: [
      {
        id: 2301,
        top: 90,
        left: 60,
        width: 8,
        height: 940,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#4F46E5",
        borderColor: "#4F46E5",
        isEditMode: false,
      },
      {
        id: 2302,
        top: 370,
        left: 60,
        width: 8,
        height: 250,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#22D3EE",
        borderColor: "#22D3EE",
        isEditMode: false,
      },
    ],
  },
  {
    id: 3001,
    title: "Երկկողմանի (երկու սյուն)",
    backgroundColor: "#F8FAFC",
    isEditMode: false,
    dimension: {
      format: "custom",
      title: "Custom",
      width: 794,
      height: 1123,
      preview: { width: 248, height: 350 },
    },
    contentBlocks: [
      {
        id: 3101,
        top: 80,
        left: 60,
        width: 290,
        height: 130,
        rotation: 0,
        zIndex: 1,
        contentType: "title",
        defaultContent: "",
        content: "Արթուր Կարապետյան",
        fontSize: 42,
        fontWeight: "700",
        color: "#0F172A",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 3102,
        top: 230,
        left: 60,
        width: 290,
        height: 210,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Կոնտակտներ</strong><br/>
📞 +374 91 123 456<br/>
✉️ artur@example.am<br/>
🌐 linkedin.com/in/artur<br/><br/>
<strong>Լեզուներ</strong><br/>
Հայերեն · Ռուսերեն · Անգլերեն`,
        fontSize: 15,
        fontWeight: "400",
        color: "#1F2937",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 3103,
        top: 80,
        left: 380,
        width: 340,
        height: 220,
        rotation: 0,
        zIndex: 1,
        contentType: "description",
        defaultContent: "",
        content:
          "Մենեջեր տվյալների ոլորտում՝ խորը տեխնիկական գիտելիքներով և թիմեր կառուցելու փորձով։ Էֆեկտիվ հաղորդակցումը և առաքումը՝ իմ գլխավոր սկզբունքներն են։",
        fontSize: 18,
        fontWeight: "400",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 3104,
        top: 320,
        left: 380,
        width: 340,
        height: 280,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Աշխատանքային փորձ</strong><br/>
ՏՏ Ծրագրերի մենեջեր · Nimbus Tech · 2019 — ներկայում<br/>
- Վարել եմ բազմաբաժին նախագծեր՝ մինչև 12 մասնագետով թիմերով։<br/>
- Ստեղծել եմ KPI համակարգ, որը կրճատել է սխալները 30%-ով։<br/><br/>
Scrum Master · FastWave · 2015 — 2019`,
        fontSize: 16,
        fontWeight: "400",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 3105,
        top: 610,
        left: 380,
        width: 340,
        height: 240,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Հմտություններ</strong><br/>
Scrum · Kanban · OKR · Stakeholder management · Jira · Trello<br/><br/>
<strong>Կրթություն</strong><br/>
Երևանի Պետական Համալսարան · Տեղեկատվական Տեխնոլոգիաներ<br/>
2011 — 2015`,
        fontSize: 15,
        fontWeight: "400",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
    ],
    imageBlocks: [
      {
        id: 3201,
        top: 730,
        left: 70,
        width: 260,
        height: 180,
        rotation: 0,
        zIndex: 1,
        path: "https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        isEditMode: false,
      },
    ],
    shapeBlocks: [
      {
        id: 3301,
        top: 300,
        left: 60,
        width: 290,
        height: 2,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#CBD5F5",
        borderColor: "#CBD5F5",
        isEditMode: false,
      },
      {
        id: 3302,
        top: 600,
        left: 60,
        width: 290,
        height: 2,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#CBD5F5",
        borderColor: "#CBD5F5",
        isEditMode: false,
      },
    ],
  },
  {
    id: 4001,
    title: "Ստեղծագործ օրիգինալ",
    backgroundColor: "#FFF7ED",
    isEditMode: false,
    dimension: {
      format: "a4",
      title: "A4",
      width: 794,
      height: 1123,
      preview: { width: 248, height: 350 },
    },
    contentBlocks: [
      {
        id: 4101,
        top: 140,
        left: 120,
        width: 450,
        height: 120,
        rotation: 0,
        zIndex: 2,
        contentType: "title",
        defaultContent: "",
        content: "Հրանտ Ստեփանյան",
        fontSize: 48,
        fontWeight: "700",
        color: "#9A3412",
        backgroundColor: "transparent",
        fontFamily: "Playfair Display",
        textAlign: "center",
        isEditMode: false,
      },
      {
        id: 4102,
        top: 280,
        left: 100,
        width: 490,
        height: 160,
        rotation: 0,
        zIndex: 2,
        contentType: "description",
        defaultContent: "",
        content:
          "Ստեղծագործ գրող և բովանդակության ռազմավար․ 10-ամյա փորձով՝ կազմել եմ պատմական, մշակութային և բիզնես ուղղվածության նյութեր։",
        fontSize: 18,
        fontWeight: "400",
        color: "#7C2D12",
        backgroundColor: "transparent",
        fontFamily: "Sans-serif",
        textAlign: "center",
        isEditMode: false,
      },
      {
        id: 4103,
        top: 460,
        left: 90,
        width: 520,
        height: 280,
        rotation: 0,
        zIndex: 2,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Գլխավոր նախագծեր</strong><br/>
• "Մեր քաղաքը" քաղաքային պատմությունների հավաքածու՝ 15k ընթերցող։<br/>
• "Բիզնեսի լեզուն" մասնագիտական բլոգ՝ 40+ հոդվածներով։<br/><br/>
<strong>Պատվիրատուներ</strong><br/>
IAB Armenia · Bookinist · Aurora Forum · Impact Hub`,
        fontSize: 17,
        fontWeight: "400",
        color: "#6B2F1C",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
    ],
    imageBlocks: [
      {
        id: 4201,
        top: 60,
        left: 570,
        width: 150,
        height: 150,
        rotation: 0,
        zIndex: 1,
        path: "https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        isEditMode: false,
      },
    ],
    shapeBlocks: [
      {
        id: 4301,
        top: 100,
        left: 520,
        width: 220,
        height: 220,
        rotation: 15,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#FED7AA",
        borderColor: "#FB923C",
        isEditMode: false,
      },
      {
        id: 4302,
        top: 420,
        left: 80,
        width: 550,
        height: 4,
        rotation: 0,
        zIndex: 1,
        shapeType: "rectangle",
        backgroundColor: "#FDBA74",
        borderColor: "#FDBA74",
        isEditMode: false,
      },
    ],
  },
  {
    id: 5001,
    title: "Տեխնիկական մանրամասն",
    backgroundColor: "#F3F4F6",
    isEditMode: false,
    dimension: {
      format: "a4",
      title: "A4",
      width: 794,
      height: 1123,
      preview: { width: 248, height: 350 },
    },
    contentBlocks: [
      {
        id: 5101,
        top: 70,
        left: 80,
        width: 360,
        height: 100,
        rotation: 0,
        zIndex: 1,
        contentType: "title",
        defaultContent: "",
        content: "Նարեկ Մարտիրոսյան",
        fontSize: 38,
        fontWeight: "700",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 5102,
        top: 70,
        left: 480,
        width: 220,
        height: 180,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Կոնտակտ</strong><br/>
☎️ +374 99 765 432<br/>
✉️ narek@dev.am<br/>
💻 github.com/narekmart<br/>
📍 Երևան, Հայաստան`,
        fontSize: 14,
        fontWeight: "400",
        color: "#1F2937",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 5103,
        top: 220,
        left: 80,
        width: 620,
        height: 320,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Աշխատանքային փորձ</strong><br/>
Senior Software Engineer · CloudLayer · 2020 — ներկայում<br/>
- Կառուցել եմ բարձրաբեռնված միկրոսերվիսներ (Go, Kubernetes)։<br/>
- Կազմել եմ CI/CD հոսքեր՝ GitHub Actions + ArgoCD։<br/><br/>
Software Engineer · NetBuild · 2016 — 2020<br/>
- Աշխատել եմ Realtime համակարգերի վրա (Node.js + Redis)։<br/>
- Մշակել եմ REST և GraphQL API-ներ։`,
        fontSize: 15,
        fontWeight: "400",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
      {
        id: 5104,
        top: 560,
        left: 80,
        width: 620,
        height: 250,
        rotation: 0,
        zIndex: 1,
        contentType: "text",
        defaultContent: "",
        content: `<strong>Տեխնոլոգիաներ</strong><br/>
Go · TypeScript · React · PostgreSQL · AWS · Terraform · Kafka<br/><br/>
<strong>Սերտիֆիկացիաներ</strong><br/>
AWS Solutions Architect Associate · 2023<br/>
CKA · Certified Kubernetes Administrator · 2022`,
        fontSize: 15,
        fontWeight: "400",
        color: "#111827",
        backgroundColor: "transparent",
        fontFamily: "Inter",
        textAlign: "left",
        isEditMode: false,
      },
    ],
    imageBlocks: [],
    shapeBlocks: [
      {
        id: 5301,
        top: 200,
        left: 70,
        width: 650,
        height: 2,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#D1D5DB",
        borderColor: "#D1D5DB",
        isEditMode: false,
      },
      {
        id: 5302,
        top: 540,
        left: 70,
        width: 650,
        height: 2,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#D1D5DB",
        borderColor: "#D1D5DB",
        isEditMode: false,
      },
      {
        id: 5303,
        top: 840,
        left: 70,
        width: 650,
        height: 2,
        rotation: 0,
        zIndex: 0,
        shapeType: "rectangle",
        backgroundColor: "#D1D5DB",
        borderColor: "#D1D5DB",
        isEditMode: false,
      },
    ],
  },
];
